name: Close Issue Automatically

on:
  issues:
    types: [opened, reopened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue with a comment
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "This issue has been auto-closed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
